#!/usr/bin/python3

import os
import configparser
import subprocess

configPath = '/opt/scuttle/'

def scanI2C(bus):
    cmd = ["i2cdetect", "-y", "-r", str(bus)]

    i2c_output = subprocess.check_output(cmd).decode("utf-8").split('\n')

    del i2c_output[0]
    del i2c_output[-1]

    i2c_output = [line[4:].strip().replace(' ', '').split('--') for line in i2c_output]
    i2c_output = [["0x"+i for i in line if i is not ''] for line in i2c_output]
    i2c_output = [[int(device, 16) for device in line] for line in i2c_output if line != []][0]

    return i2c_output

if os.geteuid() is 0:

    if not os.path.exists(configPath):
        os.makedirs(configPath)

    config = configparser.ConfigParser()

    config['DEFAULT'] = {'ServerAliveInterval': '45',
                        'Compression': 'yes',
                        'CompressionLevel': '9'}

    config['bitbucket.org'] = {}
    config['bitbucket.org']['User'] = 'hg'

    config['topsecret.server.com'] = {}
    topsecret = config['topsecret.server.com']

    topsecret['Port'] = '50022'     # mutates the parser
    topsecret['ForwardX11'] = 'no'  # same here

    config['DEFAULT']['ForwardX11'] = 'yes'

    with open(configPath+'scuttle.ini', 'w') as configfile:
        config.write(configfile)

else:
    print("Please run as root!")
    exit(1)