label: 'Default Robot Config'

robot:

    # Length of wheel base (m)
    wheel_base: 0.355

    # Maximum Linear Velocity (m/s)
    max_linear_velocity: 0.45

    # Maximum Angular Velocity (rad/s)
    max_angular_velocity: 2.7

    # Wheel Loop Frequency (Hz)
    wheel_frequency: 50

    # Maximum Linear Velocity During Goal-to-Goal Navigation (m/s)
    max_traveling_linear_velocity: 0.2

    # Maximum Angular Velocity During Goal-to-Goal Navigation (m/s)
    max_traveling_angular_velocity: 0.75

    # Heading Controller PID Gains    
    heading_Kp: 0
    heading_Ki: 0
    heading_Kd: 0

    # Left Wheel Parameters
    l_wheel:

        # Wheel radius (m)
        wheel_radius: 0.04165

        # Number of teeth on motor pulley
        motor_pulley_teeth: 15

        # Number of teeth on wheel pulley
        wheel_pulley_teeth: 30

        # Closed Loop Left Wheel Speed PID Gains    
        Kp: 0
        Ki: 0
        Kd: 0

        # Motor Parameters
        encoder:

            # I2C bus id
            i2c_bus: 1

            # Encoder address
            address: 0x40

            # Indicate if the encoder direction needs to be inverted
            invert: True

        # Motor Parameters
        motor:

            # Motor PWM frequency in Hz
            pwm_frequency: 150

            # Indicate if the motor direction needs to be inverted
            invert: False

            # Motor GPIO Pins
            motor_pins: (11,12)
            
            # Motor RPM
            rpm: 200

            # Indicate motor decay mode (SLOW/FAST)
            decay_mode: SLOW

    # Right wheel parameters
    r_wheel:

        # Wheel radius (m)
        wheel_radius: 0.04165

        # Number of teeth on motor pulley
        motor_pulley_teeth: 15

        # Number of teeth on wheel pulley
        wheel_pulley_teeth: 30

        # Closed Loop Right Wheel Speed PID Gains    
        Kp: 0
        Ki: 0
        Kd: 0

        # Encoder Parameters
        encoder:

            # I2C bus id
            i2c_bus: 1

            # Encoder address
            address: 0x41

            # Indicate if the encoder direction needs to be inverted
            invert: False

        # Motor Parameters
        motor:

            # Motor PWM frequency in Hz
            pwm_frequency: 150

            # Indicate if the motor direction needs to be inverted
            invert: False

            # Motor GPIO Pins
            motor_pins: (15,16)

            # Motor RPM
            rpm: 200
            
            # Indicate motor decay mode (SLOW/FAST)
            decay_mode: SLOW
