# This file is part of the ddcontroller library (https://github.com/ansarid/ddcontroller).
# Copyright (C) 2022  Daniyal Ansari

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

label: 'Default Robot Config'

robot:

    # Wheel Base Distance (m)
    wheel_base: 0.100

    # Maximum Linear Velocity (m/s)
    max_linear_velocity: 0.8

    # Maximum Angular Velocity (rad/s)
    max_angular_velocity: 12

    # Wheel Loop Frequency (Hz)
    wheel_frequency: 50

    # Maximum Linear Velocity During Goal-to-Goal Navigation (m/s)
    max_traveling_linear_velocity: 0.3

    # Maximum Angular Velocity During Goal-to-Goal Navigation (m/s)
    max_traveling_angular_velocity: 6

    # Heading Controller PID Gains
    heading_Kp: 12
    heading_Ki: 0
    heading_Kd: 0

    # Left Wheel Parameters
    left_wheel:

        # Wheel Radius (m)
        wheel_radius: 0.030

        # Number Of Teeth On Motor Pulley
        motor_pulley_teeth: 1

        # Number Of Teeth On Wheel Pulley
        wheel_pulley_teeth: 1

        # Open or closed loop control
        closed_loop: False

        # Closed Loop Wheel Speed PID Gains
        Kp: 0
        Ki: 0
        Kd: 0

        encoder:

            # I2C Bus ID
            i2c_bus: 1

            # Encoder Address
            address: 0x41

            # Flag To Indicate If The Encoder Readings Need To Be Inverted
            invert: True

        motor:

            # Motor PWM Frequency (Hz)
            pwm_frequency: 100

            # Indicate If The Motor Duty Cycle Needs To Be Inverted
            invert: False

            # Motor Pins
            pins:
                - 0
                - 1

            # Indicate Motor Decay Mode (SLOW/FAST)
            decay_mode: SLOW

    # Right Wheel Parameters
    right_wheel:

        # Wheel Radius (m)
        wheel_radius: 0.030

        # Number Of Teeth On Motor Pulley
        motor_pulley_teeth: 1

        # Number Of Teeth On Wheel Pulley
        wheel_pulley_teeth: 1

        # Open or closed loop control
        closed_loop: False

        # Closed Loop Wheel Speed PID Gains
        Kp: 0
        Ki: 0
        Kd: 0

        encoder:

            # I2C Bus ID
            i2c_bus: 1

            # Encoder Address
            address: 0x42

            # Flag To Indicate If The Encoder Readings Need To Be Inverted
            invert: False

        motor:

            # Motor PWM Frequency (Hz)
            pwm_frequency: 100

            # Indicate If The Motor Duty Cycle Needs To Be Inverted
            invert: False

            # Motor Pins
            pins:
                - 2
                - 3

            # Indicate Motor Decay Mode (SLOW/FAST)
            decay_mode: SLOW
