label: None

scuttle:

    chassis:

        # Wheel base (L) in meters.
        wheel_base: 0.355

        # Wheel radius in meters
        wheel_radius: 0.04165

        # Maximum Linear Velocity (m/s)
        maximum_linear_velocity: 0.45

        # Maximum Angular Velocity (rad/s)
        maximum_angular_velocity: 2.7

        # Wheel information
        wheels:

            # I2C bus id
            i2c_bus_id: 1

            # Wheel Loop Frequency
            wheel_frequency: 50

            # Motor PWM frequency in Hz
            pwm_frequency: 150

            # Open loop wheel speed control
            openloop: True

            # Left wheel details
            l_wheel:

                minimum_forward_duty: 0.22
                maximum_forward_duty: 1
                minimum_forward_angular_velocity: 1
                maximum_forward_angular_velocity: 10
                minimum_backward_duty: -0.22
                maximum_backward_duty: -1
                minimum_backward_angular_velocity: -1
                maximum_backward_angular_velocity: -10

                # minimum_matching_forward_duty: 1
                # maximum_matching_forward_duty: 1
                # minimum_matching_backward_duty: 1
                # maximum_matching_backward_duty: 1

                encoder:
                    # Encoder address
                    address: 0x40

                    # Flag to indicate if the encoder data needs to be inverted
                    invert: True

                motor:

                    # Flag to indicate if the motor duty cycle needs to be inverted
                    invert: False

                    # GPIO pins to be used to control the left motor
                    motor:

                        # GPIO pin designated as digital
                        digital: 11

                        # GPIO pin designed as PWM
                        pwm: 12

            # Right wheel details
            r_wheel:

                minimum_forward_duty: 0.22
                maximum_forward_duty: 1
                minimum_forward_angular_velocity: 1
                maximum_forward_angular_velocity: 10
                minimum_backward_duty: -0.22
                maximum_backward_duty: -1
                minimum_backward_angular_velocity: -1
                maximum_backward_angular_velocity: -10

                # minimum_matching_forward_duty: 1
                # maximum_matching_forward_duty: 1
                # minimum_matching_backward_duty: 1
                # maximum_matching_backward_duty: 1

                encoder:
                    # Encoder address
                    address: 0x41

                    # Flag to indicate if the encoder data needs to be inverted
                    invert: False

                motor:

                    # Flag to indicate if the motor duty cycle needs to be inverted
                    invert: False

                    # GPIO pins to be used to control the left motor
                    motor:

                        # GPIO pin designated as digital
                        digital: 15

                        # GPIO pin designed as PWM
                        pwm: 16

        # Platform controlling the robot
        # RPi - Raspberry PI
        # Beagle - Beagle
        # TISK - TI SK board
        # Nano - NVIDIA Jetson Nano board
        motor_control_platform: 'RPi'

    # Sensor specific information
    sensors: None