label: 'Default SCUTTLE Config'

scuttle:

    chassis:

        # Wheel base (L) in meters.
        wheel_base: 0.355

        # Wheel radius in meters
        wheel_radius: 0.04165

        # Number of teeth on motor pulley
        motor_pulley: 13

        # Number of teeth on wheel pulley
        wheel_pulley: 25

        # Maximum Linear Velocity (m/s)
        maximum_linear_velocity: 0.45

        # Maximum Angular Velocity (rad/s)
        maximum_angular_velocity: 2.7

        # Wheel information
        wheels:

            # I2C bus id
            i2c_bus_id: 1

            # Wheel Loop Frequency
            wheel_frequency: 50

            # Motor PWM frequency in Hz
            pwm_frequency: 150

            # Left wheel details
            l_wheel:

                encoder:
                    # Encoder address
                    address: 0x40

                    # Flag to indicate if the encoder data needs to be inverted
                    invert: True

                motor:

                    # Indicate if the motor duty cycle needs to be inverted
                    invert: False

                    # GPIO pin designated as digital
                    digital: 11

                    # GPIO pin designed as PWM
                    pwm: 12

            # Right wheel details
            r_wheel:

                encoder:
                    # Encoder address
                    address: 0x41

                    # Flag to indicate if the encoder data needs to be inverted
                    invert: False

                motor:

                    # Indicate if the motor duty cycle needs to be inverted
                    invert: False

                    # GPIO pin designated as digital
                    digital: 36

                    # GPIO pin designed as PWM
                    pwm: 35

        # Platform controlling the robot
        # RPi - Raspberry PI
        # Beagle - Beagle
        # TISK - TI SK board
        # Nano - NVIDIA Jetson Nano board
        motor_control_platform: 'RPi'

    # Sensor specific information
    sensors: None