scuttle:

    chassis:

        # Wheel base (L) in meters.
        wheel_base: 0.355

        # Wheel radius in meters
        wheel_radius: 0.04165

        # Wheel information
        wheels:

            # I2C bus id
            i2c_bus_id: 1

            # Motor PWM frequency in Hz
            pwm_frequency: 150

            # Left wheel details
            l_wheel:

                encoder:
                    # Encoder address
                    address: 0x40

                    # Flag to indicate if the encoder data needs to be inverted
                    invert: True

                # GPIO pins to be used to control the left motor
                motor_control_gpio:

                    # GPIO pin designated as digital
                    digital: 11

                    # GPIO pin designed as PWM
                    pwm: 12

                    # Flag to indicate if the motor duty cycle needs to be inverted
                    invert: False

            # Right wheel details
            r_wheel:

                encoder:
                    # Encoder address
                    address: 0x41

                    # Flag to indicate if the encoder data needs to be inverted
                    invert: False

                # GPIO pins to be used to control the left motor
                motor_control_gpio:

                    # GPIO pin designated as digital
                    digital: 15

                    # GPIO pin designed as PWM
                    pwm: 16

                    # Flag to indicate if the motor duty cycle needs to be inverted
                    invert: False

        # Platform controlling the robot
        # RPi - Raspberry PI
        # Beagle - Beagle
        # TISK - TI SK board
        # Nano - NVIDIA Jetson Nano board
        motor_control_platform: 'RPi'

    # Sensor specific information
    sensors: null
